version: '3'

services:
  database:
    image: postgres:10
    env_file: .env
    restart: always
    volumes:
      - database:/var/lib/postgresql

  api:
    build: .
    env_file: .env
    restart: always

volumes:
  database:
