version: '3'

services:
  proxy:
    build:
      context: nginx-proxy
      args:
        PROXY_SSL: "true"
        PROXY_DOMAIN: "localhost"
    #volumes:
    restart: always
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
