CREATE TABLE frames (
  id VARCHAR(400) NOT NULL,
  project VARCHAR(400) NOT NULL,
  start_at TIMESTAMP DEFAULT NULL,
  end_at TIMESTAMP DEFAULT NULL,
  tags JSONB DEFAULT NULL,
  sync_date TIMESTAMP DEFAULT NOW(),
  UNIQUE (id)
)
